export const QUEUE_ACTION_TYPES = {
  ADD_TO_QUEUE: "ADD_TO_QUEUE",
  ADD_PLAYLIST_TO_QUEUE: "ADD_PLAYLIST_TO_QUEUE",
  TOGGLE_QUEUE_HIDDEN: "TOGGLE_QUEUE_HIDDEN",
  REMOVE_FROM_QUEUE: "REMOVE_FROM_QUEUE",
  CLEAR_QUEUE: "CLEAR_QUEUE",
};
