export const RECENTS_ACTION_TYPES = {
  ADD_TO_RECENTS: "ADD_TO_RECENTS",
  TOGGLE_IS_RECENTS_FETCHING: "TOGGLE_IS_RECENTS_FETCHING",
  SET_RECENTLY_PLAYED_FROM_FIREBASE: "SET_RECENTLY_PLAYED_FROM_FIREBASE",
  CLEAR_RECENTLY_PLAYED: "CLEAR_RECENTLY_PLAYED",
};
