export const PLAYER_ACTION_TYPES = {
  PLAY_TRACK: "PLAY_TRACK",
  SET_CURR_TIME: "SET_CURR_TIME",
  SET_DURATION: "SET_DURATION",

  TOGGLE_IS_PAUSED: "TOGGLE_IS_PAUSED",
  TOGGLE_IS_MUTED: "TOGGLE_IS_MUTED",
  TOGGLE_IS_REPEATED: "TOGGLE_IS_REPEATED",
};
