export const PLAYLISTS_ACTION_TYPES = {
  ADD_TO_PLAYLISTS: "ADD_TO_PLAYLISTS",
  REMOVE_PLAYLIST_FROM_PLAYLISTS: "REMOVE_PLAYLIST_FROM_PLAYLISTS",
  REMOVE_TRACK_FROM_PLAYLIST: "REMOVE_TRACK_FROM_PLAYLIST",
  SET_IS_PLAYLIST_PLAYING: "SET_IS_PLAYLIST_PLAYING",
  TOGGLE_IS_PLAYLISTS_PLAYING: "TOGGLE_IS_PLAYLISTS_PLAYING",
  SET_PLAYLISTS_FROM_FIREBASE: "SET_PLAYLISTS_FROM_FIREBASE",
  CLEAR_PLAYLISTS: "CLEAR_PLAYLISTS",
};
